export interface MovieI {
    ID: number,
    Name: string,
    Describe: string,
    EndTime: Date,
    StartTime: Date,
    ImageSrc: string,
    Places: Number[][],
    NormalPrice: number,
    VIPPrice: number,
    Is3D: boolean,
    IsIMAX: boolean,
    Is4D: boolean,
    IsScreenX: boolean,
    LanguageName: string,
    SubtitlesName: string,
    Director: string,
    AgeCategory: string,
    Category: string,
    ScreenSize: string,
    MovieID: number,
    RoomID: number,
    MovieInfoID: number
}